### ISSUE TITLE
What version of SWORD does this currently expect?

### ISSUE THREAD

**Issue by alerque** [tobias-klein/node-sword-interface#7]
I just tried to update AUR packaging for this so that I can update Ezra and ran into trouble. I'm guessing it now doesn't work with stable released SWORD? Is there a minimum version or commit for this to build against system libraries now?

```
Linking system SWORD library!
  TOUCH Release/obj.target/sword.stamp
  CXX(target) Release/obj.target/node_sword_interface/src/sword_backend/file_system_helper.o
  CXX(target) Release/obj.target/node_sword_interface/src/sword_backend/module_helper.o
  CXX(target) Release/obj.target/node_sword_interface/src/sword_backend/module_store.o
  CXX(target) Release/obj.target/node_sword_interface/src/sword_backend/string_helper.o
  CXX(target) Release/obj.target/node_sword_interface/src/sword_backend/strongs_entry.o
  CXX(target) Release/obj.target/node_sword_interface/src/sword_backend/repository_interface.o
  CXX(target) Release/obj.target/node_sword_interface/src/sword_backend/module_search.o
../src/sword_backend/module_search.cpp: In member function ‘std::vector<Verse> ModuleSearch::getModuleSearchResults(std::string, std::string, SearchType, bool, bool)’:
../src/sword_backend/module_search.cpp:97:18: error: ‘SEARCHFLAG_STRICTBOUNDARIES’ was not declared in this scope
   97 |         flags |= SEARCHFLAG_STRICTBOUNDARIES;
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~
make: *** [node_sword_interface.target.mk:131: Release/obj.target/node_sword_interface/src/sword_backend/module_search.o] Error 1
make: Leaving directory '/home/caleb/projects/aur/nodejs-sword-interface/pkg/nodejs-sword-interface/usr/lib/node_modules/node-sword-interface/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 5.7.3-arch1-1
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/caleb/projects/aur/nodejs-sword-interface/pkg/nodejs-sword-interface/usr/lib/node_modules/node-sword-interface
gyp ERR! node -v v12.17.0
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sword-interface@0.141.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
```

**Comment by tobias-klein** [comment]
It's https://crosswire.org/svn/sword/trunk@3747

**Comment by alerque** [comment]
Thanks, that works.
